version: "3.9"

services:
  db:
    container_name: club_db
    image: mysql
    volumes:
      - "./data/db:/var/lib/mysql"
      - ./src/db/aiprompts.sql:/docker-entrypoint-initdb.d/aiprompts.sql
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  web:
    container_name: club_web
    build: ./src
    working_dir: /src/
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
